[functions.stripe-connect-onboard]
verify_jwt = false

[functions.create-link-checkout-session]
verify_jwt = false

[functions.create-creator-subscription]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-connect-status]
verify_jwt = false

[functions.increment-link-click]
verify_jwt = false

[functions.increment-profile-view]
verify_jwt = false

[functions.admin-get-users]
verify_jwt = false

[functions.admin-get-user-overview]
verify_jwt = false

[functions.generate-signed-urls]
verify_jwt = false

[functions.send-link-content-email]
verify_jwt = false

[functions.link-referral]
verify_jwt = false

[functions.send-referral-invite]
verify_jwt = false
